### ISSUE TITLE
java.util.NoSuchElementException: @ ServerHandler.java:39

### ISSUE THREAD

**Issue by rumeshmadhusanka** [rumeshmadhusanka/distributed-chat-server#15]
Exception in thread "Thread-1" Exception in thread "Thread-1" java.util.NoSuchElementException: No line found
java.util.NoSuchElementException: No line found
        at java.base/java.util.Scanner.nextLine(Scanner.java:1651)      at java.base/java.util.Scanner.nextLine(Scanner.java:1651)

        at Server.ServerHandler.run(ServerHandler.java:39)
        at Server.ServerHandler.run(ServerHandler.java:39)

**Comment by rumeshmadhusanka** [comment]
start 2 servers; connect a client

**Comment by rumeshmadhusanka** [comment]
@ThaminduR

**Comment by rumeshmadhusanka** [comment]
solved #17
